### ISSUE TITLE
Servers that only support DH/ECDH

### ISSUE THREAD

**Issue by richmoore** [WestpointLtd/tls_prober#14]
Currently servers that only support DH/ECDH will not fingerprint properly.

**Comment by tomato42** [comment]
since most probes are TLSv1.0 based, servers that disable it, will have different signal too

**Comment by richmoore** [comment]
Yes, I really need to make it figure out which version is supported and use that. It should then ignore the version in most of the probe results (except those where that is specifically what is being tested).

**Comment by tomato42** [comment]
there are some servers which will negotiate TLS1.0 if you send TLS1.0 Client Hello but will negotiate SSLv3 if you send TLS1.1 or TLS1.2 client hello

so differences in behaviour between different versions are interesting

for now, I think we just need two set of probes, the current TLSv1.0's and new set with TLSv1.2

since the set of default ciphersuites and extensions needs to be updated with new protocol versions, I'm not sure if autodetection of supported version and using that for scan will give robust probes...

**Comment by tomato42** [comment]
though it may be good idea to have at least one or two TLSv1.1 probes, as there was a set of Apache servers with a bug that disabled TLSv1.1 support leaving TLSv1.0 and TLSv1.2 working, making the server negotiate TLSv1.0 when presented with TLSv1.1 (and I've heard rumours that they were not the only ones)
